// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiAb_GnbAKh94T0-k2qhY3gF7heVygRUk',
    appId: '1:783866924480:web:22d2a9f425484271910c25',
    messagingSenderId: '783866924480',
    projectId: 'fir-2-c3904',
    authDomain: 'fir-2-c3904.firebaseapp.com',
    storageBucket: 'fir-2-c3904.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0tNhIlKbNw6aPV9A25nB_E9962S9Mg_0',
    appId: '1:783866924480:android:90b94cf409fad412910c25',
    messagingSenderId: '783866924480',
    projectId: 'fir-2-c3904',
    storageBucket: 'fir-2-c3904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmsB-mdtlw1XZq8jLc9Ks1JbbbqW5_CA',
    appId: '1:783866924480:ios:4a91f53f93915110910c25',
    messagingSenderId: '783866924480',
    projectId: 'fir-2-c3904',
    storageBucket: 'fir-2-c3904.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmsB-mdtlw1XZq8jLc9Ks1JbbbqW5_CA',
    appId: '1:783866924480:ios:4a91f53f93915110910c25',
    messagingSenderId: '783866924480',
    projectId: 'fir-2-c3904',
    storageBucket: 'fir-2-c3904.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiAb_GnbAKh94T0-k2qhY3gF7heVygRUk',
    appId: '1:783866924480:web:30ae8c4f5d1d4ec0910c25',
    messagingSenderId: '783866924480',
    projectId: 'fir-2-c3904',
    authDomain: 'fir-2-c3904.firebaseapp.com',
    storageBucket: 'fir-2-c3904.appspot.com',
  );
}
